/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.the_ica.applications.commons.messages.avro;

import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.SchemaStore;
import org.apache.avro.specific.SpecificData;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class MtmTradeMessageValue extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -6976536379346620235L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"MtmTradeMessageValue\",\"namespace\":\"com.the_ica.applications.commons.messages.avro\",\"fields\":[{\"name\":\"date\",\"type\":\"int\"},{\"name\":\"mtms\",\"type\":{\"type\":\"array\",\"items\":\"double\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<MtmTradeMessageValue> ENCODER =
      new BinaryMessageEncoder<MtmTradeMessageValue>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<MtmTradeMessageValue> DECODER =
      new BinaryMessageDecoder<MtmTradeMessageValue>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<MtmTradeMessageValue> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<MtmTradeMessageValue> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<MtmTradeMessageValue>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this MtmTradeMessageValue to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a MtmTradeMessageValue from a ByteBuffer. */
  public static MtmTradeMessageValue fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public int date;
  @Deprecated public java.util.List<java.lang.Double> mtms;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public MtmTradeMessageValue() {}

  /**
   * All-args constructor.
   * @param date The new value for date
   * @param mtms The new value for mtms
   */
  public MtmTradeMessageValue(java.lang.Integer date, java.util.List<java.lang.Double> mtms) {
    this.date = date;
    this.mtms = mtms;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return date;
    case 1: return mtms;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: date = (java.lang.Integer)value$; break;
    case 1: mtms = (java.util.List<java.lang.Double>)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'date' field.
   * @return The value of the 'date' field.
   */
  public java.lang.Integer getDate() {
    return date;
  }

  /**
   * Sets the value of the 'date' field.
   * @param value the value to set.
   */
  public void setDate(java.lang.Integer value) {
    this.date = value;
  }

  /**
   * Gets the value of the 'mtms' field.
   * @return The value of the 'mtms' field.
   */
  public java.util.List<java.lang.Double> getMtms() {
    return mtms;
  }

  /**
   * Sets the value of the 'mtms' field.
   * @param value the value to set.
   */
  public void setMtms(java.util.List<java.lang.Double> value) {
    this.mtms = value;
  }

  /**
   * Creates a new MtmTradeMessageValue RecordBuilder.
   * @return A new MtmTradeMessageValue RecordBuilder
   */
  public static com.the_ica.applications.commons.messages.avro.MtmTradeMessageValue.Builder newBuilder() {
    return new com.the_ica.applications.commons.messages.avro.MtmTradeMessageValue.Builder();
  }

  /**
   * Creates a new MtmTradeMessageValue RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new MtmTradeMessageValue RecordBuilder
   */
  public static com.the_ica.applications.commons.messages.avro.MtmTradeMessageValue.Builder newBuilder(com.the_ica.applications.commons.messages.avro.MtmTradeMessageValue.Builder other) {
    return new com.the_ica.applications.commons.messages.avro.MtmTradeMessageValue.Builder(other);
  }

  /**
   * Creates a new MtmTradeMessageValue RecordBuilder by copying an existing MtmTradeMessageValue instance.
   * @param other The existing instance to copy.
   * @return A new MtmTradeMessageValue RecordBuilder
   */
  public static com.the_ica.applications.commons.messages.avro.MtmTradeMessageValue.Builder newBuilder(com.the_ica.applications.commons.messages.avro.MtmTradeMessageValue other) {
    return new com.the_ica.applications.commons.messages.avro.MtmTradeMessageValue.Builder(other);
  }

  /**
   * RecordBuilder for MtmTradeMessageValue instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<MtmTradeMessageValue>
    implements org.apache.avro.data.RecordBuilder<MtmTradeMessageValue> {

    private int date;
    private java.util.List<java.lang.Double> mtms;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.the_ica.applications.commons.messages.avro.MtmTradeMessageValue.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.date)) {
        this.date = data().deepCopy(fields()[0].schema(), other.date);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.mtms)) {
        this.mtms = data().deepCopy(fields()[1].schema(), other.mtms);
        fieldSetFlags()[1] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing MtmTradeMessageValue instance
     * @param other The existing instance to copy.
     */
    private Builder(com.the_ica.applications.commons.messages.avro.MtmTradeMessageValue other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.date)) {
        this.date = data().deepCopy(fields()[0].schema(), other.date);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.mtms)) {
        this.mtms = data().deepCopy(fields()[1].schema(), other.mtms);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'date' field.
      * @return The value.
      */
    public java.lang.Integer getDate() {
      return date;
    }

    /**
      * Sets the value of the 'date' field.
      * @param value The value of 'date'.
      * @return This builder.
      */
    public com.the_ica.applications.commons.messages.avro.MtmTradeMessageValue.Builder setDate(int value) {
      validate(fields()[0], value);
      this.date = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'date' field has been set.
      * @return True if the 'date' field has been set, false otherwise.
      */
    public boolean hasDate() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'date' field.
      * @return This builder.
      */
    public com.the_ica.applications.commons.messages.avro.MtmTradeMessageValue.Builder clearDate() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'mtms' field.
      * @return The value.
      */
    public java.util.List<java.lang.Double> getMtms() {
      return mtms;
    }

    /**
      * Sets the value of the 'mtms' field.
      * @param value The value of 'mtms'.
      * @return This builder.
      */
    public com.the_ica.applications.commons.messages.avro.MtmTradeMessageValue.Builder setMtms(java.util.List<java.lang.Double> value) {
      validate(fields()[1], value);
      this.mtms = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'mtms' field has been set.
      * @return True if the 'mtms' field has been set, false otherwise.
      */
    public boolean hasMtms() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'mtms' field.
      * @return This builder.
      */
    public com.the_ica.applications.commons.messages.avro.MtmTradeMessageValue.Builder clearMtms() {
      mtms = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public MtmTradeMessageValue build() {
      try {
        MtmTradeMessageValue record = new MtmTradeMessageValue();
        record.date = fieldSetFlags()[0] ? this.date : (java.lang.Integer) defaultValue(fields()[0]);
        record.mtms = fieldSetFlags()[1] ? this.mtms : (java.util.List<java.lang.Double>) defaultValue(fields()[1]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<MtmTradeMessageValue>
    WRITER$ = (org.apache.avro.io.DatumWriter<MtmTradeMessageValue>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<MtmTradeMessageValue>
    READER$ = (org.apache.avro.io.DatumReader<MtmTradeMessageValue>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
